version: '3.4'

networks:
  vuttr:
    ipam:
      config:
      - subnet: 172.11.1.0/24

services:
  app:
    container_name: app
    networks:
      vuttr:
        ipv4_address: 172.11.1.2
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/app
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
      PORT: 4200
      HOST: 0.0.0.0
      VUE_APP_API: http://172.11.1.3:4000
    ports:
    - 4400:4400
    - 4500:4500
    entrypoint: /bin/sh -c '/ws/app.sh; tail -f'

  api:
    container_name: api
    networks:
      vuttr:
        ipv4_address: 172.11.1.3
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/api
    entrypoint: /bin/sh -c 'npm install && npm start; tail -f'
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
      PORT: 4000
      HOST: 0.0.0.0
    ports:
    - 4000:4000
    - 4010:4010
    - 4020:4020

  e2e:
    container_name: e2e
    networks:
      vuttr:
        ipv4_address: 172.11.1.4
    volumes:
    - ./:/ws
    image: node:8.16.0-alpine
    working_dir: /ws/e2e
    entrypoint: /bin/sh -c 'npm install; tail -f'
    environment:
      APP_URL: http://172.11.1.2:4200
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59

  hub:
    container_name: hub
    image: selenium/hub:2.53.1
    networks:
      vuttr:
        ipv4_address: 172.11.1.5
    ports:
     - 4444:4444
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59

  firefox:
    container_name: firefox
    networks:
      vuttr:
        ipv4_address: 172.11.1.6
    image: selenium/node-firefox-debug:2.53.1
    ports:
    - 9000
    - 5901:5900
    volumes:
    - /dev/shm:/dev/shm
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      HUB_HOST: hub
      HUB_PORT: 4444
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    depends_on:
    - app
    - hub

  chrome:
    container_name: chrome
    networks:
      vuttr:
        ipv4_address: 172.11.1.7
    image: selenium/node-chrome-debug:2.53.1
    ports:
    - 9000
    - 5902:5900
    volumes:
    - /dev/shm:/dev/shm
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      HUB_HOST: hub
      HUB_PORT: 4444
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    depends_on:
    - app
    - hub

